apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli-test
  namespace: kafka
  labels:
    app: kafka-cli-test
spec:
  containers:
    - name: kafka-cli
      image: quay.io/strimzi/kafka:1.2.0-kafka-4.2.0
      command:
        - /bin/sh
        - -c
        - sleep 3600
  restartPolicy: Never